owner: thomas-merz
repo: upptime

sites:
  - name: dm-Homepage
    url: https://www.dm.de/
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Dm_Logo.svg/320px-Dm_Logo.svg.png
  - name: 1Password
    url: $URL_1PASSWORD
    icon: https://w7.pngwing.com/pngs/950/276/png-transparent-1password-password-manager-android-lastpass-android-trademark-logo-1-password.png
  - name: ADFS
    url: $URL_ADFS
    icon: https://cdn2.iconfinder.com/data/icons/metro-uinvert-dock/256/Microsoft.png
    expectedStatusCodes:
      - 404
  - name: ALI
    url: $URL_ALI
  - name: Alpha
    url: $URL_ALPHA
  - name: bitwarden
    url: $URL_BITWARDEN
    icon: https://w7.pngwing.com/pngs/842/316/png-transparent-bitwarden-alt-macos-bigsur-icon.png
  - name: Condeco
    url: $URL_CONDECO
    icon: https://cdn.freelogovectors.net/wp-content/uploads/2021/11/condeco-logo-freelogovectors.net_.png
  - name: dm-DWH
    url: $URL_DMDWH
    icon: https://s3-symbol-logo.tradingview.com/microstrategy--big.svg
  - name: dm-GPT
    url: $URL_DMGPT
    icon: https://static.vecteezy.com/system/resources/previews/021/972/603/non_2x/minsk-belarus-03-27-2023-openai-and-chatgpt-logo-artifical-chatbot-system-chat-bot-button-for-web-app-and-phone-icon-symbol-editorial-illustration-free-vector.jpg
  - name: dm-IAM
    url: $URL_DMIAM
    icon: https://logowik.com/content/uploads/images/aws-iam2657.jpg
  - name: dm-Rechnungen
    url: $URL_DMRECHNUNGEN
    icon: https://cornelia-pikal.de/wp-content/uploads/2020/04/payment_invoice.png
  - name: dm-SAP
    url: $URL_DMSAP
    icon: https://e7.pngegg.com/pngimages/646/840/png-clipart-sap-logo-illustration-sap-se-computer-icons-sap-erp-wtf-miscellaneous-blue.png
  - name: dm-Sharepoint
    url: $URL_DMSHAREPOINT
    icon: https://www.liblogo.com/img-logo/sh7810fc31-sharepoint-logo-file-microsoft-office-sharepoint-2019-present-svg-wikimedia.png
    expectedStatusCodes:
      - 401
  - name: dm-Travel
    url: $URL_DMTRAVEL
    icon: https://img.freepik.com/premium-vector/detailed-travel-logo_23-2148616612.jpg?w=2000
  - name: Gitlab
    url: $URL_GITLAB
    icon: https://logowik.com/content/uploads/images/gitlab8368.jpg
  - name: Jira
    url: $URL_JIRA
    icon: https://iconape.com/wp-content/files/ew/71098/png/jira-3.png
  - name: Microsoft Login
    url: login.microsoft.com
    icon: https://cdn2.iconfinder.com/data/icons/metro-uinvert-dock/256/Microsoft.png
  - name: Microsoft Teams
    url: https://teams.microsoft.com
  - name: Microsoft Outlook
    url: https://outlook.office.com
    expectedStatusCodes:
      - 200
      - 417
  - name: Nutrax
    url: $URL_NUTRAX
    icon: https://www.softwareabc24.de/logos/timesec-zeiterfassung-software-logo-2024.png
  - name: VPN
    url: $URL_VPN
    icon: https://cdn.imgbin.com/13/0/14/imgbin-cisco-anyconnect-vpn-client-computer-icons-cisco-systems-portable-network-graphics-virtual-private-network-cisco-anyconnect-vpn-icon-KAr0B2nUVEF34rRa14QbNqfXn.jpg
    __dangerous__insecure: true
  - name: Wiki
    url: $URL_WIKI
    icon: https://img.icons8.com/color/452/atlassian-confluence.png
assignees:
  - thomas-merz

status-website:
  # https://github.com/upptime/upptime/discussions/222#discussioncomment-302627
  robotsText: "User-agent: * \n Disallow: /"
  metaTags:
    - name: "color-scheme"
      content: "light"
    - name: "robots"
      content: "noindex"
  # https://github.com/upptime/upptime/discussions/54#discussioncomment-215193
  #publish: true
  baseUrl: /upptime
  logoUrl: https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Dm_Logo.svg/320px-Dm_Logo.svg.png
  name: Upptime
  introTitle: "**Upptime** monitor and status page"
  introMessage: This is the status page which uses **real-time** data from Thomas Merz' [GitHub repository](https://github.com/thomas-merz/upptime). [![Average time to resolve an issue](http://isitmaintained.com/badge/resolution/thomas-merz/upptime.svg)](http://isitmaintained.com/project/thomas-merz/upptime)
  # https://upptime.js.org/docs/faq/#how-do-i-remove-the-powered-by-upptime-in-the-footer-of-my-website
  i18n:
    footer: This page is powered by [Upptime](https://upptime.js.org)
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# https://upptime.js.org/docs/configuration#ci-schedule
###workflowSchedule:
###  graphs: "0 0 * * *"  # default
###  responseTime: "0 23 * * *"  # default
###  staticSite: "0 0 * * *"  # default
###  summary: "0 0 * * *"  # default
###  updateTemplate: "0 1 * * *"  # default: 00:00
###  updates: "0 4 * * *"  # default: 03:00
###  uptime: "*/5 * * * *"  # default

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
