owner: thomas-merz
repo: upptime

sites:
  - name: dm-Homepage
    url: https://www.dm.de/
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Dm_Logo.svg/320px-Dm_Logo.svg.png
#    maxResponseTime: 3000
  - name: Alpha
    url: $URL_ALPHA
#    maxResponseTime: 3000
  - name: Nutrax
    url: $URL_NUTRAX
#    maxResponseTime: 3000
  - name: Gitlab
    url: $URL_GITLAB
    icon: https://logowik.com/content/uploads/images/gitlab8368.jpg
#    maxResponseTime: 3000
  - name: Jira
    url: $URL_JIRA
    #icon: https://logowik.com/content/uploads/images/jira2966.logowik.com.webp
    #icon: https://marketplace-api.looker.com/block-icons/jira_icon.png
    icon: https://iconape.com/wp-content/files/ew/71098/png/jira-3.png
#    maxResponseTime: 3000
  - name: VPN
    url: $URL_VPN
    icon: https://cdn.imgbin.com/13/0/14/imgbin-cisco-anyconnect-vpn-client-computer-icons-cisco-systems-portable-network-graphics-virtual-private-network-cisco-anyconnect-vpn-icon-KAr0B2nUVEF34rRa14QbNqfXn.jpg
    __dangerous__insecure: true
  - name: Wiki
    url: $URL_WIKI
    icon: https://img.icons8.com/color/452/atlassian-confluence.png
#    maxResponseTime: 3000
  - name: ADFS
    url: $URL_ADFS
    icon: https://cdn2.iconfinder.com/data/icons/metro-uinvert-dock/256/Microsoft.png
    expectedStatusCodes:
      - 404
#    maxResponseTime: 3000
  - name: Microsoft Login
    url: login.microsoft.com
    icon: https://cdn2.iconfinder.com/data/icons/metro-uinvert-dock/256/Microsoft.png
#    maxResponseTime: 3000
  - name: Microsoft Teams
    url: https://teams.microsoft.com
  - name: Microsoft Outlook
    url: https://outlook.office.com
    expectedStatusCodes:
      - 200
      - 417
assignees:
  - thomas-merz

status-website:
  # https://github.com/upptime/upptime/discussions/222#discussioncomment-302627
  robotsText: "User-agent: * \n Disallow: /"
  metaTags:
    - name: "color-scheme"
      content: "light"
    - name: "robots"
      content: "noindex"
  # https://github.com/upptime/upptime/discussions/54#discussioncomment-215193
  #publish: true
  baseUrl: /upptime
  logoUrl: https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Dm_Logo.svg/320px-Dm_Logo.svg.png
  name: Upptime
  introTitle: "**Upptime** monitor and status page"
  introMessage: This is the status page which uses **real-time** data from Thomas Merz' [GitHub repository](https://github.com/thomas-merz/upptime). [![Average time to resolve an issue](http://isitmaintained.com/badge/resolution/thomas-merz/upptime.svg)](http://isitmaintained.com/project/thomas-merz/upptime)
  # https://upptime.js.org/docs/faq/#how-do-i-remove-the-powered-by-upptime-in-the-footer-of-my-website
  i18n:
    footer: This page is powered by [Upptime](https://upptime.js.org)
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# https://upptime.js.org/docs/configuration#ci-schedule
###workflowSchedule:
###  graphs: "0 0 * * *"  # default
###  responseTime: "0 23 * * *"  # default
###  staticSite: "0 0 * * *"  # default
###  summary: "0 0 * * *"  # default
###  updateTemplate: "0 1 * * *"  # default: 00:00
###  updates: "0 4 * * *"  # default: 03:00
###  uptime: "*/5 * * * *"  # default

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
