# Change these first
owner: thomas-merz # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: dm-Homepage
    url: $URL_DMDE
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Dm_Logo.svg/320px-Dm_Logo.svg.png
#    maxResponseTime: 3000
  - name: Alpha
    url: $URL_ALPHA
#    maxResponseTime: 3000
  - name: Gitlab
    url: $URL_GITLAB
#    maxResponseTime: 3000
### TODO:  - name: Jira
### TODO:   url: $URL_JIRA
#    maxResponseTime: 3000
  - name: Wiki
    url: $URL_WIKI
#    maxResponseTime: 3000

assignees:
  - thomas-merz

status-website:
  # https://github.com/upptime/upptime/discussions/222#discussioncomment-302627
  robotsText: "User-agent: * \n Disallow: /"
  metaTags:
    - name: "color-scheme"
      content: "light"
    - name: "robots"
      content: "noindex"
  # https://github.com/upptime/upptime/discussions/54#discussioncomment-215193
  #publish: true
  baseUrl: /upptime
  logoUrl: https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Dm_Logo.svg/320px-Dm_Logo.svg.png
  name: Upptime
  introTitle: "**Upptime** monitor and status page"
  introMessage: This is the status page which uses **real-time** data from Thomas Merz' [GitHub repository](https://github.com/thomas-merz/upptime).
  # https://upptime.js.org/docs/faq/#how-do-i-remove-the-powered-by-upptime-in-the-footer-of-my-website
  i18n:
    footer: This page is powered by [Upptime](https://upptime.js.org)
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# https://upptime.js.org/docs/configuration#ci-schedule
###workflowSchedule:
###  graphs: "0 0 * * *"  # default
###  responseTime: "0 23 * * *"  # default
###  staticSite: "0 0 * * *"  # default
###  summary: "0 0 * * *"  # default
###  updateTemplate: "0 1 * * *"  # default: 00:00
###  updates: "0 4 * * *"  # default: 03:00
###  uptime: "*/5 * * * *"  # default

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
